import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/navigation";

import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FurGroove",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="mt-24">
          <Image
            src="/logo.webp"
            alt="FurGroove"
            width={700}
            height={300}
            className="mx-auto"
          />
          <h1 className="text-center text-3xl uppercase tracking-wide mt-4">
            10th of August
          </h1>
          <h2 className="text-center text-xl uppercase tracking-wide mb-14">
            BOOT 3 | Rotterdam, NL
          </h2>
        </header>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
