import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/navigation";

import { Button } from "@/components/ui/button";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FurGroove",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="mt-24">
          <a href="../">
            <img
              src="/logo.webp"
              alt="FurGroove"
              width={700}
              height={300}
              className="mx-auto cursor-pointer transition-transform hover:scale-105"
            />
          </a>
          <h1 className="mt-4 text-center text-3xl uppercase tracking-wide">
            10th of August
          </h1>
          <h2 className="mb-14 text-center text-xl uppercase tracking-wide">
            BOOT 3 | Rotterdam, NL
          </h2>
        </header>
        <Navigation />
        {children}
        <footer className="flex flex-col">
          <a
            href="https://t.me/furgroove"
            target="_blank"
            className="mx-auto mt-24 text-xl font-medium"
          >
            <Button className="w-64">Telegram Group Chat</Button>
          </a>
          <a
            href="https://t.me/furgrooveinfo"
            target="_blank"
            className="mx-auto my-4 text-xl font-medium"
          >
            <Button className="w-64">Telegram Channel</Button>
          </a>
          <a
            href="https://furgroove.club/archive/"
            target="_blank"
            className="mx-auto mb-24 text-xl font-medium"
          >
            <Button className="w-64">Website Archive</Button>
          </a>
          <a href="../">
            <img
              src="/logo.webp"
              alt=""
              height={100}
              width={500}
              className="mx-auto mb-12 cursor-pointer transition-transform hover:scale-105"
            />
          </a>
        </footer>
      </body>
    </html>
  );
}
